name: Build and deploy frontend to GitHub Pages

on:
  push:
    branches:
      - "actions"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          git --version
