name: Build and deploy frontend to GitHub Pages

on:
  push:
    branches:
      - "actions"

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: node:17-slim
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd frontend; yarn
      - name: Fix Contract conflict
        run: |
          rm -rf frontend/node_modules/\@usedapp/core/node_modules/\@ethersproject/
      - name: Build frontend
        run: |
          cd frontend; yarn build



